export const API = process.env.APT_URL
export const LEARN_API = process.env.LEARN_API_URL
export const SDKAPPID = process.env.SDKAPPID
export const SPECIAL_MESSAGE = 'HKYIM_SPECIAL_MESSAGE'
export const CALLBACK_MESSAGE = 'HKYIM_CALLBACK_MESSAGE'
export const IM_CALLBACK_MESSAGE = 'HKYIM_IMCALLBACK_MESSAGE'
export const IM_CHANGE_TABKEY = 'HKYIM_IM_CHANGE_TABKEY'
export const HKYIM_IMLOGIN = 'HKYIM_IMLOGIN'
export const HKYIM_IMREDAY = 'HKYIM_IMREDAY'
export const HKYIM_IMERROR = 'HKYIM_IMERROR'
export const HKYIM_IMONMESSAGE = 'HKYIM_IMONMESSAGE'
export const HKYIM_IM_INLINE_NUM = 'HKYIM_IM_INLINE_NUM'
export const HKYIM_IM_LIVE_STATUS = 'HKYIM_IM_LIVE_STATUS'
export const HKYIM_IM_LIKE_NUM = 'HKYIM_IM_LIKE_NUM'
export const HKYIM_KICKED_OUT = 'HKYIM_KICKED_OUT'
export const HKYIM_PUSH_ADDR_CHANGED = 'HKYIM_LIVE_PUSH_CHANGED'
export const HKYIM_PULL_ADDR_CHANGED = 'HKYIM_LIVE_PULL_CHANGED'
export const IM_CALLBACK_ASK_BEHAVIOR = 'IM_CALLBACK_ASK_BEHAVIOR'
export const IM_CALLBACK_TAB_BEHAVIOR = 'IM_CALLBACK_TAB_BEHAVIOR'
export const HKYIM_TAB_CHANGE = 'HKYIM_TAB_CHANGE'
export const HKYIM_TAB_CHAT = '_CHAT'
export const HKYIM_TAB_ACTIVITY = '_ACTIVITY'
export const HKYIM_TAB_CLASSES = '_CLASSES'
export const HKYIM_TAB_ASK = '_ASK'
export const HKYIM_TAB_GOODS = '_STUDENT_GOODS'
export const HKYIM_EMOJI_DISPLAY_CHANGE = 'HKYIM_EMOJI_DISPLAY_CHANGE'
export const HKYIM_MASK_CLICK = 'HKYIM_MASK_CLICK'
export const HKYIM_IM_INIT_MESSAGE = 'HKYIM_IM_INIT_MESSAGE'


export const HKYIM_GROUP_FORBIDDENLIST = 'HKYIM_GROUP_FORBIDDENLIST'
export const HKYIM_GROUP_GETGROUPMEMBERLIST = 'HKYIM_GROUP_GETGROUPMEMBERLIST'
export const HKYIM_SWITCH_ONLINENUM = 'HKYIM_SWITCH_ONLINENUM'
export const HKYIM_GROUP_SHELF_SHOW = 'HKYIM_GROUP_SHELF_SHOW'
export const HKYIM_GROUP_SHELF_HIDE = 'HKYIM_GROUP_SHELF_HIDE'
export const HKYIM_GROUP_COMMON_CONTROL = 'HKYIM_GROUP_COMMON_CONTROL'

export const HKYIM_MULTI_PULL_ADDR_CHANGED = 'HKYIM_MULTI_PULL_ADDR_CHANGED'
export const HKYIM_MULTI_PUSH_ADDR_CHANGED = 'HKYIM_MULTI_PUSH_ADDR_CHANGED'

export const IFRAME_URL = process.env.IFRAME_URL
export const TEST_URL = process.env.TES_URL

export const SDK_SHELF_CLICK_EVENT = 'shelfClick'

export const SPECIAL_MESSAGE_TYPES = {
  ASK: 'ASK',
  ACTIVITY: 'ACTIVITY',
}
export const URL_BLACKLIST = ['tabList']

export const HKYIM_IFRAME_LOAD = 'HKYIM_IFRAME_LOAD'
export const HKYIM_GET_GROUP_PROFILE = 'HKYIM_GET_GROUP_PROFILE'
export const HKYIM_SEND_MESSAGE = 'HKYIM_SEND_MESSAGE'
export const HKYIM_SEND_MESSAGE_LIKE = 'HKYIM_SEND_MESSAGE_LIKE'
export const HKYIM_GET_GROUP_MEMBERLIST = 'HKYIM_GET_GROUP_MEMBERLIST'
export const HKYIM_GET_MESSAGELIST = 'HKYIM_GET_MESSAGELIST'
export const HKYIM_SEND_CUSTSOM_IMAGE = 'HKYIM_SEND_CUSTSOM_IMAGE'
export const HKYIM_GET_GROUP_USERPROFILE = 'HKYIM_GET_GROUP_USERPROFILE'


export const MULTI_PULL_ADDR_CHANGED = 'MULTI_PULL_ADDRESS_CHANGED'
export const MULTI_PUSH_ADDR_CHANGED = 'MULTI_PUSH_ADDRESS_CHANGED'
export const LIVE_PUSH_ADDR_CHANGED = 'PUSH_ADDRESS_CHANGED'
export const LIVE_PULL_ADDR_CHANGED = 'PULL_ADDRESS_CHANGED'
export const GROUP_LIKE_NUM = 'GROUP_LIKE_NUM'
export const GROUP_SILENCE = 'GROUP_SILENCE'
export const GROUP_URL_SENDER = 'GROUP_URL_SENDER'
export const GROUP_SHELF_SHOW = 'GROUP_SHELF_SHOW'
export const GROUP_SHELF_HIDE = 'GROUP_SHELF_HIDE'
export const GROUP_COMMON_CONTROL = 'GROUP_COMMON_CONTROL'
export const CUSTOM_MSG = 'CUSTOM_MSG'
export const GROUP_EVENT_NOTIFY = 'GROUP_EVENT_NOTIFY'
export const IMG_PRELOAD = 'IMG_PRELOAD'
export const LIVE_STATUS_CHANGED = 'LIVE_STATUS_CHANGED'